import os
def habittracker():
	os.system('cls' if os.name == 'nt' else 'clear')
	print("\nExcellence is not an act, but a habit' ~ Socrates" )
	print("==================================================")
	print("BASIC HYGIENE & APPEARANCE ")
	print("==================================================")
	print(" - Brush teeth, floss & mouthwash, Frequency: Daily")
	print(" - Bathe, Moisturise & Vaseline (+fragrance)")
	print(" - Shave")
	print(" - Trim Nails")
	print(" - Haircut")
	print("==================================================")
	print("HEALTH & WELLBEING")
	print("==================================================")
	print(" - Sleep (11:00 - 06:30)")
	print(" - Exercise")
	print(" - Mindfulness")
	print("==================================================")
	print("WISDOM & KNOWLEDGE")
	print("==================================================")
	print(" - Self-help")
	print(" - Programming")
	print(" - Textbook")
	print("==================================================")
	print("SOCIAL INTERACTION")
	print("==================================================")
	print(" - Self-help")
	print(" - Programming")
	print(" - Textbook")
	print("")
	#switchViews()

	#This method will need to be remade with tables